name: Ping a Render (API)

"on":
  schedule:
    - cron: "*/10 23,0-4 * * *"
  workflow_dispatch:

jobs:
  ping: 
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Ping al endpoint /health
        run: |
          curl -fsS --max-time 90 --retry 2 --retry-delay 5 \
            "${{ secrets.URL_BACKEND }}/health"